### PR TITLE
TPM12: Exports NVPermissions, Localities, Digest, Nonce

### PR DESCRIPTION
**Pull request by ChriMarMe**
Removed unused const digestSize, nonceSize

### CODE REVIEW

**Comment by ChriMarMe** [comment]
--- PASS: TestUnpackMalformedBytes (0.00s)
=== RUN   TestPoll
--- PASS: TestPoll (0.00s)
PASS
ok  	github.com/google/go-tpm/tpmutil	0.078s
?   	github.com/google/go-tpm/tpmutil/mssim	[no test files]
FAIL

I have no idea what's going on ¯\_(ツ)_/¯

**Comment by ChriMarMe** [comment]
This is work in progress. When ready for final review I will ping!

**Comment by ChriMarMe** [comment]
Ok, if @twitchy-jsonp  or @josephlr could have a look and tell me why the tests fail, I would fix it and we'll good to go for merging :)

**Comment by twitchy-jsonp** [comment]
Not sure whats going on, that cirrus output seems to be missing some detail.

Running `go test -v ./...` in a fresh machine has a few failures, but not sure if the cirrus setup has the dependencies necessary to avoid them.

```
jsonp@RedShell:~/go-tpm> go test -v ./...
go: downloading github.com/google/go-tpm-tools v0.0.0-20190906225433-1614c142f845
go: extracting github.com/google/go-tpm-tools v0.0.0-20190906225433-1614c142f845
# github.com/google/go-tpm-tools/simulator/internal
In file included from /home/jsonp/go/pkg/mod/github.com/google/go-tpm-tools@v0.0.0-20190906225433-1614c142f845/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/LibSupport.h:54:0,
                 from /home/jsonp/go/pkg/mod/github.com/google/go-tpm-tools@v0.0.0-20190906225433-1614c142f845/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/Tpm.h:47,
                 from ../go/pkg/mod/github.com/google/go-tpm-tools@v0.0.0-20190906225433-1614c142f845/simulator/internal/internal.go:39:
/home/jsonp/go/pkg/mod/github.com/google/go-tpm-tools@v0.0.0-20190906225433-1614c142f845/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/Ossl/TpmToOsslSym.h:47:25: fatal error: openssl/aes.h: No such file or directory
 #include <openssl/aes.h>
                         ^
compilation terminated.
# github.com/google/go-tpm/tpm [github.com/google/go-tpm/tpm.test]
tpm/pcrs_test.go:142:40: undefined: locZero
tpm/tpm_test.go:40:27: undefined: digest
tpm/tpm_test.go:41:11: undefined: digest
tpm/tpm_test.go:235:43: undefined: locZero
tpm/tpm_test.go:239:44: undefined: locZero
tpm/tpm_test.go:243:42: undefined: nvPerOwnerWrite
tpm/tpm_test.go:324:27: undefined: locZero
tpm/tpm_test.go:352:29: undefined: locZero
?   	github.com/google/go-tpm/examples/tpm-clear	[no test files]
?   	github.com/google/go-tpm/examples/tpm-genaik	[no test files]
?   	github.com/google/go-tpm/examples/tpm-keys	[no test files]
?   	github.com/google/go-tpm/examples/tpm-sign	[no test files]
?   	github.com/google/go-tpm/examples/tpm-takeownership	[no test files]
?   	github.com/google/go-tpm/examples/tpm2-ekcert	[no test files]
?   	github.com/google/go-tpm/examples/tpm2-nvread	[no test files]
?   	github.com/google/go-tpm/examples/tpm2-seal-unseal	[no test files]
FAIL	github.com/google/go-tpm/tpm [build failed]
=== RUN   TestEncodeDecodeCreationData
--- PASS: TestEncodeDecodeCreationData (0.00s)
=== RUN   TestDecodeReadPCRs
--- PASS: TestDecodeReadPCRs (0.00s)
=== RUN   TestSingleEncodeDecodeTPMLSelection
--- PASS: TestSingleEncodeDecodeTPMLSelection (0.00s)
=== RUN   TestMultiArgsEncodeDecodeTPMLSelection
--- PASS: TestMultiArgsEncodeDecodeTPMLSelection (0.00s)
=== RUN   TestDecodeReadClock
--- PASS: TestDecodeReadClock (0.00s)
=== RUN   TestDecodeGetCapability
--- PASS: TestDecodeGetCapability (0.00s)
=== RUN   TestEncodeLoad
--- PASS: TestEncodeLoad (0.00s)
=== RUN   TestDecodeLoad
--- PASS: TestDecodeLoad (0.00s)
=== RUN   TestEncodeCreate
--- PASS: TestEncodeCreate (0.00s)
=== RUN   TestDecodeCreatePrimary
--- PASS: TestDecodeCreatePrimary (0.00s)
=== RUN   TestEncodePolicyPCR
--- PASS: TestEncodePolicyPCR (0.00s)
=== RUN   TestDecodeStartAuthSession
--- PASS: TestDecodeStartAuthSession (0.00s)
=== RUN   TestDecodeCreate
--- PASS: TestDecodeCreate (0.00s)
=== RUN   TestEncodeUnseal
--- PASS: TestEncodeUnseal (0.00s)
=== RUN   TestDecodeUnseal
--- PASS: TestDecodeUnseal (0.00s)
=== RUN   TestEncodeQuote
--- PASS: TestEncodeQuote (0.00s)
=== RUN   TestDecodeQuote
--- PASS: TestDecodeQuote (0.00s)
=== RUN   TestDecodeReadPublic
--- PASS: TestDecodeReadPublic (0.00s)
=== RUN   TestEncodeEvictControl
--- PASS: TestEncodeEvictControl (0.00s)
=== RUN   TestEncodeAuthArea
--- PASS: TestEncodeAuthArea (0.00s)
=== RUN   TestEncodeSensitiveArea
--- PASS: TestEncodeSensitiveArea (0.00s)
=== RUN   TestEncodeTPMLPCRSelection
--- PASS: TestEncodeTPMLPCRSelection (0.00s)
=== RUN   TestECCParamsEncodeDecode
--- PASS: TestECCParamsEncodeDecode (0.01s)
=== RUN   TestSignEncode
=== RUN   TestSignEncode/AlgNull
=== RUN   TestSignEncode/AlgSHA256
--- PASS: TestSignEncode (0.00s)
    --- PASS: TestSignEncode/AlgNull (0.00s)
    --- PASS: TestSignEncode/AlgSHA256 (0.00s)
=== RUN   TestError
--- PASS: TestError (0.00s)
=== RUN   TestRunCommandErr
--- PASS: TestRunCommandErr (0.00s)
PASS
ok  	github.com/google/go-tpm/tpm2	0.037s
=== RUN   TestCredentialActivation
--- PASS: TestCredentialActivation (0.00s)
PASS
ok  	github.com/google/go-tpm/tpm2/credactivation	0.028s
FAIL	github.com/google/go-tpm/tpm2/test [build failed]
=== RUN   TestEmulatorReadWriteCloserMultipleReads
--- PASS: TestEmulatorReadWriteCloserMultipleReads (0.00s)
=== RUN   TestEmulatorReadWriteCloserClose
--- PASS: TestEmulatorReadWriteCloserClose (0.00s)
=== RUN   TestEmulatorReadWriteCloseReadAfterClose
--- PASS: TestEmulatorReadWriteCloseReadAfterClose (0.00s)
=== RUN   TestEmulatorReadWriteCloserReadBeforeWrite
--- PASS: TestEmulatorReadWriteCloserReadBeforeWrite (0.00s)
=== RUN   TestEmulatorReadWriteCloserDoubleWrite
--- PASS: TestEmulatorReadWriteCloserDoubleWrite (0.00s)
=== RUN   TestEmulatorReadWriteCloserDialerError
--- PASS: TestEmulatorReadWriteCloserDialerError (0.00s)
=== RUN   TestEncodingPackTypeInvalid
--- PASS: TestEncodingPackTypeInvalid (0.00s)
=== RUN   TestEncodingPackType
--- PASS: TestEncodingPackType (0.00s)
=== RUN   TestEncodingPackTypeWriteFail
--- PASS: TestEncodingPackTypeWriteFail (0.00s)
=== RUN   TestEncodingCommandHeaderInvalidBody
--- PASS: TestEncodingCommandHeaderInvalidBody (0.00s)
=== RUN   TestEncodingInvalidPack
--- PASS: TestEncodingInvalidPack (0.00s)
=== RUN   TestEncodingCommandHeaderEncoding
--- PASS: TestEncodingCommandHeaderEncoding (0.00s)
=== RUN   TestEncodingInvalidUnpack
--- PASS: TestEncodingInvalidUnpack (0.00s)
=== RUN   TestSelfMarshaler
--- PASS: TestSelfMarshaler (0.00s)
    encoding_test.go:232: Attempting to Marshal/Unmarshal []byte{0x0, 0x0} into *tpmutil.U16Bytes
    encoding_test.go:232: Attempting to Marshal/Unmarshal []byte{0x0, 0x1, 0x89} into *tpmutil.U16Bytes
    encoding_test.go:232: Attempting to Marshal/Unmarshal []byte{0x0, 0x0, 0x0, 0x0} into *tpmutil.U32Bytes
    encoding_test.go:232: Attempting to Marshal/Unmarshal []byte{0x0, 0x0, 0x0, 0x1, 0x89} into *tpmutil.U32Bytes
=== RUN   TestEncodingUnpack
--- PASS: TestEncodingUnpack (0.00s)
=== RUN   TestPartialUnpack
--- PASS: TestPartialUnpack (0.00s)
=== RUN   TestUnpackHandlesArea
--- PASS: TestUnpackHandlesArea (0.00s)
=== RUN   TestUnpackMalformedBytes
--- PASS: TestUnpackMalformedBytes (0.00s)
=== RUN   TestPoll
--- PASS: TestPoll (0.00s)
PASS
ok  	github.com/google/go-tpm/tpmutil	0.050s
?   	github.com/google/go-tpm/tpmutil/mssim	[no test files]
```

**Comment by twitchy-jsonp** [comment]
Oh okay found it I think (I got the dependencies installed but still have this error):

```
# github.com/google/go-tpm/tpm [github.com/google/go-tpm/tpm.test]
tpm/pcrs_test.go:142:40: undefined: locZero
tpm/tpm_test.go:40:27: undefined: digest
tpm/tpm_test.go:41:11: undefined: digest
tpm/tpm_test.go:235:43: undefined: locZero
tpm/tpm_test.go:239:44: undefined: locZero
tpm/tpm_test.go:243:42: undefined: nvPerOwnerWrite
tpm/tpm_test.go:324:27: undefined: locZero
tpm/tpm_test.go:352:29: undefined: locZero
FAIL	github.com/google/go-tpm/tpm [build failed]
```

**Comment by ChriMarMe** [comment]
@twitchy-jsonp Thank a lot :) next time please hit me with a hammer :)
I just "tested" the go build, but not go test....so i missed to change the tests xD
Sorry to bother you but I'm thankful for your help.

**Comment by twitchy-jsonp** [comment]
No wozzles!

**Pull request merged**
