### PR TITLE
Add golang.org/x/sys dependency to go.mod

### PR DESCRIPTION
**Pull request by awly**
It's used in TPM FD polling and was missed previously.
This should fix kokoro build too.

### CODE REVIEW

**Comment by awly** [comment]
@tmroeder FYI, I'm vendoring golang.org/x/sys/unix, only because our kokoro environment doesn't support modules yet. Are you ok with that?

**Comment by awly** [comment]
OK, since @tmroeder is OOO, i'll merge this. But we can revert later if needed.

**Comment by tmroeder** [comment]
I find it unfortunate that we have to pull in code and add an extra vendor directory so that we can poll a file description in exactly one function in tpmutil. Can we use syscall.Epoll* from the standard library instead? The epoll syscall can perform exactly the function of waiting for an fd to be ready.

I glanced at #75, and I didn't see any discussion about this.

**Comment by awly** [comment]
Good point, x/sys/unix doesn't do as much magic as I thought.
Sent https://github.com/google/go-tpm/pull/100

**Pull request merged**
