### PR TITLE
export tpm.getCapability

### PR DESCRIPTION
**Pull request by chrisfenner**
This change exports getCapability so that arbitrary capabilities may be fetched.

### CODE REVIEW

**Comment by ChriMarMe** [comment]
getCapabilities is the only function where we try to implement every subCap as an exported function, so the user don't need to take care of the returned bytearray, if there is one.

It's just a question of who should take care of the returned bytearray of getCapabilities.

**Comment by chrisfenner** [comment]
Thanks for taking a look Christopher,

The [latest version](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Main-Part-2-TPM-Structures_v1.2_rev116_01032011.pdf) of the TPM 1.2 spec defines 20 capabilities, and the current TPM 1.2 library supports 6 of them.

Until the remaining 14 are implemented, it would be good to have something callers can use if they need a capability which is not explicitly handled here.

I totally agree that the raw byte slice here is more difficult to handle. What if I renamed this function to GetCapabilityRaw and added documentation encouraging callers to use the "nice" versions exposed when available?

**Comment by ChriMarMe** [comment]
Just wrap the getCapability-Function with GetCapabilityRaw, hence they take the same arguments, you can just pass them through. Also good idea with the documentation.

**Comment by chrisfenner** [comment]
SGTM, I've renamed to GetCapabilityRaw and passed the args through to getCapability, which I've left unchanged (aside from a wording fix to the documentation - not all capabilities are information fetched from NVRAM)

**Pull request merged**
