### PR TITLE
Update go.mod dependencies

### PR DESCRIPTION
**Pull request by josephlr**
For some reason this added 151 lines to `go.sum`, but I don't think that's a big deal

Signed-off-by: Joe Richey <joerichey@google.com>

### CODE REVIEW

**Comment by ChriMarMe** [comment]
Did you do?

```
go mod tidy
```

**Comment by josephlr** [comment]
> Did you do?
> 
> ```
> go mod tidy
> ```

Yes I did, it didn't change anything

**Comment by ChriMarMe** [comment]
I tried that too. go.sum --> :hankey:

**Comment by josephlr** [comment]
> I tried that too. go.sum -->

Ya, it looks like `go.sum` will always just have a lot of lines (basically every version of every transitive dep ever used). This sucks, but it seems to be the way things are.

**Review by ChriMarMe — APPROVED** [review]

**Comment by ChriMarMe** [comment]
go mod is just a behemoth :shrug:

**Comment by ChriMarMe** [comment]
From Go Modules Reference

> A module may have a text file named go.sum in its root directory, alongside its go.mod file. The go.sum file contains cryptographic hashes of the module's direct and indirect dependencies. When the go command downloads a module .mod or .zip file into the module cache, it computes a hash and checks that the hash matches the corresponding hash in the main module's go.sum file. go.sum may be empty or absent if the module has no dependencies or if all dependencies are replaced with local directories using replace directives.

**Comment by josephlr** [comment]
@chrisfenner or @twitchy-jsonp it looks like I need a CODEOWNERS approval to merge this.

**Review by twitchy-jsonp — APPROVED** [review]

**Pull request merged**
