### PR TITLE
TPM2: Add TestCreateAndCertifyCreation counterpart for ECC key

### PR DESCRIPTION
**Pull request by ElMostafaIdrassi**
This test validates the PR #192 and is a follow up to issue #191.

### CODE REVIEW

**Comment by twitchy-jsonp** [comment]
Please fix failing test:

```
--- FAIL: TestCreateAndCertifyCreationECC (0.00s)
    tpm2_test.go:1155: Verify failed
```

**Comment by ElMostafaIdrassi** [comment]
Yes, the test should fail because the PR #192 is not merged yet. Once PR #192 gets merged, `decodeCertify` will get fixed for the case of `ECDSA` signature, and the test should normally pass.

**Comment by twitchy-jsonp** [comment]
Ah, understood. Thanks for explaining. Ive just merged #192, so this should start passing soon.

**Comment by ElMostafaIdrassi** [comment]
@twitchy-jsonp Thank you! The test is now passing. Should be good to merge this one as well.

**Pull request merged**
